In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
raw_data = pd.read_csv('mail_data.csv')

In [7]:
raw_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
mail_data = raw_data.where((pd.notnull(raw_data)),'')

In [15]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [17]:
mail_data.shape

(5572, 2)

In [21]:
mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [41]:
mail_data['Category'].value_counts()

Category
1    4825
0     747
Name: count, dtype: int64

In [43]:
ham_data = mail_data[mail_data.Category == 1]
spam_data = mail_data[mail_data.Category == 0]

In [45]:
ham_data.shape

(4825, 2)

In [47]:
spam_data.shape

(747, 2)

In [105]:
ham_sample = ham_data.sample(n=747, random_state=1)
ham_sample.shape

(747, 2)

In [107]:
new_mail_data = pd.concat([ham_sample, spam_data], axis=0)
new_mail_data['Category'].value_counts()

Category
1    747
0    747
Name: count, dtype: int64

In [109]:
X = new_mail_data['Message']
Y = new_mail_data['Category']
new_mail_data.shape

(1494, 2)

In [111]:
print(X)
print(Y)

2535                        Ok enjoy . R u there in home.
1213    Yo, the game almost over? Want to go to walmar...
522                            Shall i come to get pickle
5398    Hi. Hope you had a good day. Have a better night.
700              K..u also dont msg or reply to his msg..
                              ...
5537    Want explicit SEX in 30 secs? Ring 02073162414...
5540    ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547    Had your contract mobile 11 Mnths? Latest Moto...
5566    REMINDER FROM O2: To get 2.50 pounds free call...
5567    This is the 2nd time we have tried 2 contact u...
Name: Message, Length: 1494, dtype: object
2535    1
1213    1
522     1
5398    1
700     1
       ..
5537    0
5540    0
5547    0
5566    0
5567    0
Name: Category, Length: 1494, dtype: object

In [113]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [115]:
print(X.shape, X_train.shape, X_test.shape)

(1494,) (1195,) (299,)