#Spam Mail Prediction using Logistic Regression Model

In [55]:
# libraries imported in earlier projects will already be active thoughout the entire notebook
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [57]:
# load the csv file into a pandas dataframe
raw_data = pd.read_csv('mail_data.csv')

In [59]:
raw_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [61]:
# replacing all the null values with null string
mail_data = raw_data.where((pd.notnull(raw_data)),'')

In [63]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
mail_data

(5572, 2)

In [8]:
# label encoding
mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [9]:
mail_data['Category'].value_counts()

Category
1    4825
0     747
Name: count, dtype: int64

In [10]:
ham_data = mail_data[mail_data.Category == 1]
spam_data = mail_data[mail_data.Category == 0]

In [11]:
ham_data.shape

(4825, 2)

In [12]:
spam_data.shape

(747, 2)

In [13]:
# using undersampling to balance the dataset
ham_sample = ham_data.sample(n=747, random_state=1)
ham_sample.shape

(747, 2)

In [14]:
new_mail_data = pd.concat([ham_sample, spam_data], axis=0)
new_mail_data['Category'].value_counts()

Category
1    747
0    747
Name: count, dtype: int64

In [15]:
X = new_mail_data['Message']
Y = new_mail_data['Category']
new_mail_data.shape

(1494, 2)

In [16]:
print(X)
print(Y)

2535                        Ok enjoy . R u there in home.
1213    Yo, the game almost over? Want to go to walmar...
522                            Shall i come to get pickle
5398    Hi. Hope you had a good day. Have a better night.
700              K..u also dont msg or reply to his msg..
                              ...
5537    Want explicit SEX in 30 secs? Ring 02073162414...
5540    ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547    Had your contract mobile 11 Mnths? Latest Moto...
5566    REMINDER FROM O2: To get 2.50 pounds free call...
5567    This is the 2nd time we have tried 2 contact u...
Name: Message, Length: 1494, dtype: object
2535    1
1213    1
522     1
5398    1
700     1
       ..
5537    0
5540    0
5547    0
5566    0
5567    0
Name: Category, Length: 1494, dtype: object

In [17]:
# splitting dataset into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(1494,) (1195,) (299,)

In [19]:
# feature_extraction for train and test features
feature_extract = CountVectorizer(min_df = 1, stop_words='english', lowercase=True)

feature_extract.fit(X_train)
X_train_features = feature_extract.transform(X_train)
X_test_features = feature_extract.transform(X_test)

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [20]:
print(X_test_features)

  (0, 40)	1
  (0, 244)	1
  (0, 1646)	2
  (0, 1799)	1
  (0, 2146)	1
  (0, 2330)	1
  (0, 2477)	1
  (0, 2662)	1
  (0, 2774)	1
  (0, 2934)	1
  (0, 3431)	1
  (0, 3667)	1
  (0, 3726)	1
  (0, 3855)	1
  (1, 1069)	1
  (1, 2042)	1
  (1, 2880)	1
  (1, 2976)	1
  (2, 1303)	1
  (2, 1745)	1
  (2, 2357)	1
  (2, 2873)	1
  (3, 129)	1
  (3, 259)	1
  (3, 275)	1
  :	:
  (294, 1705)	1
  (294, 1815)	1
  (294, 3185)	1
  (294, 3445)	1
  (295, 8)	1
  (295, 2328)	1
  (295, 2477)	1
  (296, 355)	1
  (296, 730)	1
  (296, 1483)	1
  (296, 3081)	1
  (296, 3431)	1
  (296, 3666)	1
  (296, 3667)	2
  (296, 3859)	1
  (297, 694)	1
  (297, 2620)	1
  (297, 3490)	1
  (297, 3630)	1
  (298, 1228)	1
  (298, 1313)	1
  (298, 1737)	1
  (298, 1872)	1
  (298, 2134)	1
  (298, 3155)	1

In [21]:
log_model = LogisticRegression()

In [22]:
# fitting training data to instance of Logistic Regression model
log_model.fit(X_train_features, Y_train)

LogisticRegression()

In [23]:
# prediction on training data
train_pred = log_model.predict(X_train_features)
accuracy_train = accuracy_score(train_pred, Y_train)

In [24]:
print('Accuracy on training data is:', accuracy_train)
print('Precision on training data:', precision_score(train_pred, Y_train))
print('Recall on training data:', recall_score(train_pred, Y_train))

Accuracy on training data is: 0.99581589958159
Precision on training data: 1.0
Recall on training data: 0.9917081260364843

In [25]:
# prediction on test data
test_pred = log_model.predict(X_test_features)
accuracy_test = accuracy_score(test_pred, Y_test)

In [26]:
print('Accuracy on test data is:', accuracy_test)
print('Precision on test data:', precision_score(test_pred, Y_test))
print('Recall on test data:', recall_score(test_pred, Y_test))

Accuracy on test data is: 0.9698996655518395
Precision on test data: 1.0
Recall on test data: 0.9430379746835443

In [27]:
# building a predictive system
input_mail = ["I'm learning a lot about Data Science and ML Basics with GrowthPro Africa!"]
input_mail_features = feature_extract.transform(input_mail)

prediction = log_model.predict(input_mail_features)
print(prediction)

if prediction[0] == 1:
    print("Ham mail")
else:
    print("Spam mail")

[1]
Ham mail