In [1]:
# import necessary dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# load the csv file into a pandas dataframe
raw_data = pd.read_csv('mail_data.csv')

In [3]:
raw_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# replacing all the null values with null string
mail_data = raw_data.where((pd.notnull(raw_data)),'')

In [5]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
mail_data.shape

(5572, 2)

In [7]:
# label encoding
mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [8]:
mail_data['Category'].value_counts()

Category
1    4825
0     747
Name: count, dtype: int64

In [9]:
ham_data = mail_data[mail_data.Category == 1]
spam_data = mail_data[mail_data.Category == 0]

In [10]:
ham_data.shape

(4825, 2)

In [11]:
spam_data.shape

(747, 2)

In [12]:
# using undersampling to balance the dataset
ham_sample = ham_data.sample(n=747, random_state=1)
ham_sample.shape

(747, 2)

In [13]:
new_mail_data = pd.concat([ham_sample, spam_data], axis=0)
new_mail_data['Category'].value_counts()

Category
1    747
0    747
Name: count, dtype: int64

In [14]:
X = new_mail_data['Message']
Y = new_mail_data['Category']
new_mail_data.shape

(1494, 2)

In [15]:
print(X)
print(Y)

2535                        Ok enjoy . R u there in home.
1213    Yo, the game almost over? Want to go to walmar...
522                            Shall i come to get pickle
5398    Hi. Hope you had a good day. Have a better night.
700              K..u also dont msg or reply to his msg..
                              ...
5537    Want explicit SEX in 30 secs? Ring 02073162414...
5540    ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547    Had your contract mobile 11 Mnths? Latest Moto...
5566    REMINDER FROM O2: To get 2.50 pounds free call...
5567    This is the 2nd time we have tried 2 contact u...
Name: Message, Length: 1494, dtype: object
2535    1
1213    1
522     1
5398    1
700     1
       ..
5537    0
5540    0
5547    0
5566    0
5567    0
Name: Category, Length: 1494, dtype: object

In [16]:
# splitting dataset into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(1494,) (1195,) (299,)

In [18]:
# feature_extraction for train and test features
feature_extract = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)

feature_extract.fit(X_train)
X_train_features = feature_extract.transform(X_train)
X_test_features = feature_extract.transform(X_test)

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [19]:
print(X_train_features)

  (0, 1860)	0.632334209765809
  (0, 2200)	0.5141084724648797
  (0, 3456)	0.5795221528981251
  (1, 200)	0.41725550549416013
  (1, 945)	0.41725550549416013
  (1, 1210)	0.24281327244376089
  (1, 1301)	0.30354494098815954
  (1, 2072)	0.2379028064337033
  (1, 2090)	0.2703733427555401
  (1, 2376)	0.2083734240279084
  (1, 3088)	0.24281327244376089
  (1, 3209)	0.41725550549416013
  (1, 3559)	0.30743853699932633
  (2, 219)	0.3441877194897175
  (2, 284)	0.3119202116863977
  (2, 689)	0.3119202116863977
  (2, 814)	0.22478375200888534
  (2, 922)	0.25038960451252273
  (2, 1272)	0.20358037617733174
  (2, 1623)	0.3015323943725119
  (2, 2374)	0.2285099140230888
  (2, 2695)	0.3015323943725119
  (2, 2783)	0.1866369967936092
  (2, 2887)	0.3119202116863977
  (2, 2970)	0.3015323943725119
  :	:
  (1193, 1530)	0.24474858062236526
  (1193, 1931)	0.2482964055379542
  (1193, 2720)	0.24146380780929275
  (1193, 2781)	0.24474858062236526
  (1193, 2899)	0.2610476686333446
  (1193, 3133)	0.21576384632913173
  (1193, 3276)	0.2482964055379542
  (1194, 458)	0.2688029619692853
  (1194, 823)	0.1909982602077408
  (1194, 881)	0.2688029619692853
  (1194, 938)	0.24360275527464034
  (1194, 1712)	0.20075132290570086
  (1194, 1851)	0.17034851142658583
  (1194, 2418)	0.15035090951641078
  (1194, 2512)	0.2688029619692853
  (1194, 2760)	0.2688029619692853
  (1194, 2850)	0.17697703282140057
  (1194, 2914)	0.2688029619692853
  (1194, 2954)	0.2688029619692853
  (1194, 3044)	0.2688029619692853
  (1194, 3187)	0.2540617860424958
  (1194, 3332)	0.23549010074266546
  (1194, 3639)	0.23549010074266546
  (1194, 3685)	0.2232572443628497
  (1194, 3866)	0.2232572443628497

In [20]:
log_model = LogisticRegression()

In [21]:
# fitting training data to instance of Logistic Regression model
log_model.fit(X_train_features, Y_train)

LogisticRegression()

In [22]:
# prediction on training data
train_pred = log_model.predict(X_train_features)
accuracy_train = accuracy_score(train_pred, Y_train)

In [23]:
print('Accuracy on training data is:', accuracy_train)

Accuracy on training data is: 0.9841004184100418

In [24]:
# prediction on test data
test_pred = log_model.predict(X_test_features)
accuracy_test = accuracy_score(test_pred, Y_test)

In [25]:
print('Accuracy on test data is:', accuracy_test)

Accuracy on test data is: 0.9632107023411371

In [26]:
# building a predictive system
input_mail = ["This was a very interesting project!"]
input_mail_features = feature_extract.transform(input_mail)

prediction = log_model.predict(input_mail_features)
print(prediction)

if prediction[0] == 1:
    print("Ham mail")
else:
    print("Spam mail")

[1]
Ham mail